### ISSUE TITLE
Joining the team from multiple tabs causes the team score to bounce between different values

### ISSUE THREAD

**Issue by whiterook6** [mayppong/gyro#2]
To reproduce:
1. open a tab (Tab A) and choose a name and a team. (eg team ABC)
2. wait about a minute for the score to be over 1.0 spins.
3. Open another tab (Tab B) and choose a new name, and join the same team as team A (eg ABC)
4. After another minute, in Tab B, choose a new team name. (eg AB2)

symptoms:
1. In Tab A, the score still shows the second player in the original team
2. In Tab B, the team score shows team scores from both teams, one after the other.

**Comment by whiterook6** [comment]
Additionally, watching Tab B's personal score, it seems to flicker between 2 values. Almost like the team and local score are switching?

**Comment by mayppong** [comment]
I don't think it has anything to do with the number of tabs you have open. In any given tab, if you switch team, you are subscribed to 2 different channel rooms. While you are delisted from the previous Squad GenServer, you're not unsubscribed from the channel.

I've been working on this issue but it's non-trivial. However, the master branch of Phoenix Framework will provide support for this so I am waiting for the next release. In the mean time, the easier fix might be on the front-end side where we make sure to send the `leave` event up to unsubscribe from the squad channel you want to leave before joining another squad.
