### ISSUE TITLE
Send total arena score and spin rate similar to a troupe's total score and spinrate

### ISSUE THREAD

**Issue by whiterook6** [mayppong/gyro#45]
It would be wild to see the overall spin rate of the whole game.

**Comment by mayppong** [comment]
This could be completed along with #9.

**Comment by mayppong** [comment]
I finally finished a big refactoring for Arena and Scoreboard. The interfaces for them are now the same for both the arena and individual squad(troupe). It should be easy enough to implement this.

**Comment by mayppong** [comment]
Done with PR #52.

Not display by the front-end yet but the data is now being passed down to the front-end.
